### ISSUE TITLE
Revisit Planets Minimal Asteroids

### ISSUE THREAD

**Issue by kabivel** [kabivel/Sins-of-Empires#222] opened 2017-10-31 12:23 UTC
Revisit Planets Minimal Asteroids somes are set to 0 when should be 1

**Comment by Joeyxxx** [comment] 2017-10-31 12:53
Mentioned in #213 

This is part of the refinery mechanics. I assume it is intended for players to gain resources via moon mining.

**Comment by Joeyxxx** [comment] 2017-10-31 13:16
Duplicate of #108  ?

**Closed** 2017-11-07 09:17 UTC
Labels: enhancement
