### ISSUE TITLE
Minmatar diplomacy research tab no meeting requirements

### ISSUE THREAD

**Issue by sseebbee** [kabivel/Sins-of-Empires#212] opened 2017-10-27 12:56 UTC
To be able to skill Worthy Cause and Arbitrate Tariff , you need prophecy envoy BPO. But Minmatar uses Cyclone so it dosen't unlock the skills.

**Comment by Joeyxxx** [comment] 2017-10-27 13:10
Duplicate of #173

**Closed by Joeyxxx** 2017-10-27 13:10 UTC
